version: '3.8'
services:
  gateway:
    image: sinless777/gateway:latest
    deploy:
      mode: replicated
      replicas: 4

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./public.pem:/etc/ssl/cert.pem
      - ./private.pem:/etc/ssl/priv.key
    depends_on:
      - gateway
    ports:
        - 7443:7443